### ISSUE TITLE
Error yandex music track mp3

### ISSUE THREAD

**Issue by llimonix** [topi314/LavaSrc#194] opened 2024-05-12 17:27 UTC
```
2024-05-12T13:26:27.307-04:00 ERROR 1043621 --- [ack-1-thread-28] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 109915323

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.0.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-2.0.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.0.4.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.IllegalStateException: Mp3 frame not found.
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.runFrameScanLoop(Mp3FrameReader.java:76) ~[lavaplayer-2.0.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.scanForFrame(Mp3FrameReader.java:53) ~[lavaplayer-2.0.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:79) ~[lavaplayer-2.0.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33) ~[lavaplayer-2.0.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.0.4.jar!/:na]
        at com.github.topi314.lavasrc.yandexmusic.YandexMusicAudioTrack.process(YandexMusicAudioTrack.java:33) ~[lavasrc-plugin-4.0.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.0.4.jar!/:na]
        ... 4 common frames omitted
```

**Comment by topi314** [comment] 2024-05-12 17:41
Duplicate of https://github.com/topi314/LavaSrc/issues/193

**Closed by topi314** 2024-05-12 17:41 UTC
